# Generated by Django 4.2.5 on 2023-09-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psicomedic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='appointment',
            new_name='apponitment',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='irst_name',
            new_name='first_name',
        ),
    ]
