# Generated by Django 4.2.5 on 2023-09-07 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicomedic', '0002_rename_appointment_patient_apponitment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='apponitment',
        ),
        migrations.RemoveField(
            model_name='psychologist',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='psicomedic.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='psychologist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='psicomedic.psychologist'),
        ),
    ]
